### ISSUE TITLE
dsh-bio compress-gff3 incorrectly mapped to CompressBed

### ISSUE THREAD

**Issue by heuermh** [heuermh/dishevelled-bio#18]
```bash
$ dsh-bio compress-gff3 -i feature.gff3.gz -o feature.gff3.bgz
java.io.IOException: could not read BED record at line 1, caught For input string: "Ensembl"
	at org.dishevelled.bio.feature.BedReader$BedLineProcessor.processLine(BedReader.java:115)
	at com.google.common.io.CharStreams.readLines(CharStreams.java:223)
	at org.dishevelled.bio.feature.BedReader.stream(BedReader.java:77)
	at org.dishevelled.bio.tools.CompressBed.call(CompressBed.java:80)
	at org.dishevelled.bio.tools.CompressBed.main(CompressBed.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dishevelled.bio.tools.Tools.call(Tools.java:79)
	at org.dishevelled.bio.tools.Tools.main(Tools.java:266)
Caused by: java.lang.NumberFormatException: For input string: "Ensembl"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.dishevelled.bio.feature.BedRecord.valueOf(BedRecord.java:464)
	at org.dishevelled.bio.feature.BedReader$BedLineProcessor.processLine(BedReader.java:112)
	... 10 more
```

**Comment by heuermh** [comment]
Fixed by commit e93eb04849b886d611ced419b51e7c8fd4ca61ec
