### ISSUE TITLE
Native build does not link libzstd-jni correctly

### ISSUE THREAD

**Issue by heuermh** [heuermh/dishevelled-bio#24]
```
$ ./target/dsh-bio-native compress-bed \
  -i GIAB_SmallVariant_Benchmark_v4beta_GRCh37_HG002.bed.gz \
  -o GIAB_SmallVariant_Benchmark_v4beta_GRCh37_HG002.bed.zst

java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dishevelled.bio.tools.Tools.call(Tools.java:79)
	at org.dishevelled.bio.tools.Tools.main(Tools.java:276)
Caused by: java.lang.UnsatisfiedLinkError: no zstd-jni in java.library.path
Unsupported OS/arch, cannot find /darwin/x86_64/libzstd-jni.dylib or load zstd-jni from system libraries. Please try building from source the jar or providing libzstd-jni in your system.
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary(NativeLibrarySupport.java:131)
	at java.lang.ClassLoader.loadLibrary(Target_java_lang_ClassLoader.java:126)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.Runtime.loadLibrary(Runtime.java:235)
	at java.lang.System.loadLibrary(System.java:360)
	at com.github.luben.zstd.util.Native.load(Native.java:68)
	at com.github.luben.zstd.util.Native.load(Native.java:54)
	at com.github.luben.zstd.ZstdOutputStream.<clinit>(ZstdOutputStream.java:15)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:475)
	at org.apache.commons.compress.compressors.zstandard.ZstdCompressorOutputStream.<init>(ZstdCompressorOutputStream.java:83)
	at org.dishevelled.compress.Writers.writer(Writers.java:155)
	at org.dishevelled.compress.Writers.writer(Writers.java:134)
	at org.dishevelled.bio.tools.CompressBed.call(CompressBed.java:77)
	at org.dishevelled.bio.tools.CompressBed.main(CompressBed.java:140)
	... 3 more
```

**Comment by heuermh** [comment]
Added `jni-config.json` in commit e407d93dd07cbf26ea939f2b231c90d4798e18f4, which required a compile time dependency on `org.brotli.dec:0.1.2`.  Build succeeds but same result at runtime.

**Comment by heuermh** [comment]
`native-image-agent` provides the following
```
$ JAVA_HOME=.../graalvm-ce-java8-20.0.0/Contents/Home java \
  -agentlib:native-image-agent=config-output-dir=`pwd` \
  -classpath "../tools/target/appassembler/lib/*" \
  org.dishevelled.bio.tools.Tools compress-bed \
  -i GIAB_SmallVariant_Benchmark_v4beta_GRCh37_HG002.bed.gz \
  -o GIAB_SmallVariant_Benchmark_v4beta_GRCh37_HG002.bed.2.zst

$ cat jni-config.json
[
{
  "name":"com.github.luben.zstd.ZstdOutputStream",
  "fields":[
    {"name":"dstPos"},
    {"name":"srcPos"}
  ]
},
{
  "name":"org.dishevelled.bio.tools.Tools",
  "methods":[{"name":"main","parameterTypes":["java.lang.String[]"] }]
}
]

$ cat proxy-config.json
[
]

$ cat reflect-config.json
[
{
  "name":"org.dishevelled.bio.tools.CompressBed",
  "methods":[{"name":"main","parameterTypes":["java.lang.String[]"] }]
}
]

$ cat resource-config.json
{
  "resources":[
    {"pattern":"\\QMETA-INF/services/jdk.vm.ci.hotspot.HotSpotJVMCIBackendFactory\\E"},
    {"pattern":"\\QMETA-INF/services/jdk.vm.ci.services.JVMCIServiceLocator\\E"},
    {"pattern":"\\Qdarwin/x86_64/libzstd-jni.dylib\\E"}
  ],
  "bundles":[]
}
```

**Comment by heuermh** [comment]
Still an issue
```bash
$ ./target/dsh-bio-native compress-bed \
    -i GIAB_SmallVariant_Benchmark_v4beta_GRCh37_HG002.bed.gz \
    -o GIAB_SmallVariant_Benchmark_v4beta_GRCh37_HG002.bed.zst

java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.dishevelled.bio.tools.Tools.call(Tools.java:79)
	at org.dishevelled.bio.tools.Tools.main(Tools.java:294)
Caused by: java.lang.UnsatisfiedLinkError: no zstd-jni-1.5.0-4 in java.library.path
Unsupported OS/arch, cannot find /darwin/amd64/libzstd-jni-1.5.0-4.dylib or load zstd-jni-1.5.0-4 from system libraries. Please try building from source the jar or providing libzstd-jni-1.5.0-4 in your system.
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:132)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:197)
	at java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.lang.System.loadLibrary(System.java:1871)
	at com.github.luben.zstd.util.Native.load(Native.java:87)
	at com.github.luben.zstd.util.Native.load(Native.java:55)
	at com.github.luben.zstd.ZstdOutputStreamNoFinalizer.<clinit>(ZstdOutputStreamNoFinalizer.java:18)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at com.github.luben.zstd.ZstdOutputStream.<init>(ZstdOutputStream.java:73)
	at com.github.luben.zstd.ZstdOutputStream.<init>(ZstdOutputStream.java:53)
	at org.apache.commons.compress.compressors.zstandard.ZstdCompressorOutputStream.<init>(ZstdCompressorOutputStream.java:86)
	at org.dishevelled.compress.Writers.writer(Writers.java:155)
	at org.dishevelled.compress.Writers.writer(Writers.java:134)
	at org.dishevelled.bio.tools.CompressBed.call(CompressBed.java:77)
	at org.dishevelled.bio.tools.CompressBed.main(CompressBed.java:140)
	... 3 more
```

**Comment by heuermh** [comment]
Note upstream issue was closed as fixed, try again with updated metadata?
