### ISSUE TITLE
NoSuchMethodError: com.google.common.base.Stopwatch.createUnstarted()

### ISSUE THREAD

**Issue by heuermh** [heuermh/dishevelled-bio#42]
Runtime classpath problem on Spark 3.2.1
```
scala> val dac = new DishevelledAdamContext(sc)
java.lang.NoSuchMethodError:
'com.google.common.base.Stopwatch com.google.common.base.Stopwatch.createUnstarted()'
  at com.google.inject.internal.InternalInjectorCreator.<init>(InternalInjectorCreator.java:64)
  at com.google.inject.Guice.createInjector(Guice.java:87)
  at com.google.inject.Guice.createInjector(Guice.java:69)
  at com.google.inject.Guice.createInjector(Guice.java:59)
  at org.dishevelled.bio.adam.DishevelledAdamContext.<init>(DishevelledAdamContext.java:142)
  ... 47 elided
```

**Comment by heuermh** [comment]
Fixed by commit f51c329ba62ce00408456b29cab603988f882132
