### ISSUE TITLE
IllegalStateException with split-* --bytes argument

### ISSUE THREAD

**Issue by heuermh** [heuermh/dishevelled-bio#6]
```
$ dsh-split-bed -b 10k -i dvl1.200.bed
Exception in thread "main" java.lang.IllegalStateException: No match found
	at java.util.regex.Matcher.group(Matcher.java:536)
	at org.dishevelled.bio.tools.AbstractSplit.toBytes(AbstractSplit.java:160)
	at org.dishevelled.bio.tools.SplitBed.main(SplitBed.java:163)

```

**Comment by heuermh** [comment]
Fixed by commit c9b692b634a21aee9d843295d7f0bd928633b8df
