### ISSUE TITLE
Could not parse prefix from description SRR622461.10000032/1

### ISSUE THREAD

**Issue by heuermh** [heuermh/dishevelled-bio#8]
Paired FASTQ written out by ADAM `AlignmentRecordRDD.saveAsPairedFastq`:
```
$ dsh-bio interleave-fastq \
  -1 ~/data/NA12878.chrom20.ILLUMINA.bwa.CEU.low_coverage.20121211.alignments_1.fq \
  -2 ~/data/NA12878.chrom20.ILLUMINA.bwa.CEU.low_coverage.20121211.alignments_2.fq \
  -p ~/data/NA12878.chrom20.ILLUMINA.bwa.CEU.low_coverage.20121211.alignments.dsh-bio.ifq \
  -u ~/data/NA12878.chrom20.ILLUMINA.bwa.CEU.low_coverage.20121211.alignments.dsh-bio.unpaired.fq
java.io.IOException: org.dishevelled.bio.read.PairedEndFastqReaderException: could not parse prefix from description SRR622461.10000032/1
	at org.dishevelled.bio.read.PairedEndFastqReader.streamPaired(PairedEndFastqReader.java:132)
	at org.dishevelled.bio.tools.InterleaveFastq.call(InterleaveFastq.java:105)
	at org.dishevelled.bio.tools.InterleaveFastq.main(InterleaveFastq.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dishevelled.bio.tools.Tools.call(Tools.java:79)
	at org.dishevelled.bio.tools.Tools.main(Tools.java:255)
Caused by: org.dishevelled.bio.read.PairedEndFastqReaderException: could not parse prefix from description SRR622461.10000032/1
	at org.dishevelled.bio.read.PairedEndFastqReader.prefix(PairedEndFastqReader.java:216)
	at org.dishevelled.bio.read.PairedEndFastqReader$1.fastq(PairedEndFastqReader.java:92)
	at org.biojava.bio.program.fastq.StreamingFastqParser$1.complete(StreamingFastqParser.java:133)
	at org.biojava.bio.program.fastq.FastqParser$FastqParserLineProcessor.processLine(FastqParser.java:170)
	at com.google.common.io.CharStreams.readLines(CharStreams.java:225)
	at org.biojava.bio.program.fastq.FastqParser.parse(FastqParser.java:53)
	at org.biojava.bio.program.fastq.StreamingFastqParser.stream(StreamingFastqParser.java:60)
	at org.biojava.bio.program.fastq.AbstractFastqReader.stream(AbstractFastqReader.java:70)
	at org.dishevelled.bio.read.PairedEndFastqReader$2.call(PairedEndFastqReader.java:114)
	at org.dishevelled.bio.read.PairedEndFastqReader$2.call(PairedEndFastqReader.java:111)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by heuermh** [comment]
Fixed by commit d44893e015cab27cbf5f972703308203a979d56a
